### ISSUE TITLE
modify the 'wait-until-job-finish' mode used in the cell "Track progress" of notebook spectrogram_generator

### ISSUE THREAD

**Issue by cazaudo** [Project-OSmOSE/osmose-datarmor#29]
In your cell "Track progress" you make the notebook wait until all jobs are finished. This is not appropriate for notebooks deployed on datarmor , first because of its walltime (max 6h , some jobs might last much longer) and second because of unused computational resources 

I suggest going back to previous Track progress cell that simply displaying current state of nber_generated_files / total_files_tobe_generated  when you execute it , or other proposition ?

note that however this mode of tracking progress is appropriate for the adjusting spectrograms with computation time is much smaller

**Comment by cazaudo** [comment]
actually we currently do not have a proper way of informing a user that his analysis has ended through notebook , because when it closes and is restarted you lose all your variables
might be useful to have a "stand-alone" cell allowing to access to tracking information directly at kernel restarting ? or sending a mail when analysis is done could be nice too

**Comment by cazaudo** [comment]
yes this is my point , i think datarmor guys would not be happy to know that we are using their notebooks just to check a file existence.. 

for tracking progress i would prefer a cell with a one-shot execution giving generated_files / total_to_be_generated + nber of running jobs (printing directly the job id in notebook would be nice also if not too complicated) , and ideally we would have an expected time estimation of the complete analysis , and the user could close its notebook, come back and check the progress , and/or be informed by email when it ends

**Comment by Rumengol** [comment]
Estimating the duration of a program is a difficult task, even moreso on parallel tasks. The best I can think of is to use the time taken and the percentage of completion up to the checking point, but that is a very loose approximate.
The rest is easier to do and will be added.

**Comment by Rumengol** [comment]
Also, I keep forgetting to mention it but a mail is sent every time a job ends. Checking if all jobs have ended and send a mail would prove tedious at best from datarmor.

**Comment by cazaudo** [comment]
indeed , time estimation is a hard task , i think a machine learning approach would be needed here

ok let's forget about the mail then!
